services:
  frontend:
    image: z2z63/frontend
    container_name: frontend
    ports: 
      - 8000:8000
  backend:
    image: z2z63/backend
    container_name: backend
  database:
    image: z2z63/database
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=book_manager
    ports:
      - 3307:3306
    volumes:
      - ./database:/var/lib/mysql
  myredis:
    image: z2z63/myredis
    container_name: myredis
    # ports:
    #   - 6379:6379